# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 Lattice Semiconductor Corporation <www.latticesemi.com>

ifdef CONFIG_$(SPL_)LATTICE_DDR
obj-$(CONFIG_TARGET_LATTICE_RISCV_LFCPNX) += lpddr4_nexus.o
endif
